# Generated by Django 4.1.7 on 2023-04-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='link',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
